// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/portals/proto/configurator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	RewriteUrl    string                 `protobuf:"bytes,2,opt,name=rewrite_url,json=rewriteUrl,proto3" json:"rewrite_url,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	AuthHeader    string                 `protobuf:"bytes,4,opt,name=auth_header,json=authHeader,proto3" json:"auth_header,omitempty"`
	CacheTtl      string                 `protobuf:"bytes,5,opt,name=cache_ttl,json=cacheTtl,proto3" json:"cache_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSpec) Reset() {
	*x = RuleSpec{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSpec) ProtoMessage() {}

func (x *RuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSpec.ProtoReflect.Descriptor instead.
func (*RuleSpec) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{0}
}

func (x *RuleSpec) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RuleSpec) GetRewriteUrl() string {
	if x != nil {
		return x.RewriteUrl
	}
	return ""
}

func (x *RuleSpec) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RuleSpec) GetAuthHeader() string {
	if x != nil {
		return x.AuthHeader
	}
	return ""
}

func (x *RuleSpec) GetCacheTtl() string {
	if x != nil {
		return x.CacheTtl
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PortalRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *RuleSpec              `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalRule) Reset() {
	*x = PortalRule{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalRule) ProtoMessage() {}

func (x *PortalRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalRule.ProtoReflect.Descriptor instead.
func (*PortalRule) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{2}
}

func (x *PortalRule) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PortalRule) GetSpec() *RuleSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UpdateRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*PortalRule          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRulesRequest) Reset() {
	*x = UpdateRulesRequest{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRulesRequest) ProtoMessage() {}

func (x *UpdateRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRulesRequest.ProtoReflect.Descriptor instead.
func (*UpdateRulesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRulesRequest) GetRules() []*PortalRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UpdateRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRulesResponse) Reset() {
	*x = UpdateRulesResponse{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRulesResponse) ProtoMessage() {}

func (x *UpdateRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRulesResponse.ProtoReflect.Descriptor instead.
func (*UpdateRulesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{4}
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{5}
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*PortalRule          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{6}
}

func (x *ListRulesResponse) GetRules() []*PortalRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SecurityPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockExec     bool                   `protobuf:"varint,1,opt,name=block_exec,json=blockExec,proto3" json:"block_exec,omitempty"`
	AllowedImages []string               `protobuf:"bytes,2,rep,name=allowed_images,json=allowedImages,proto3" json:"allowed_images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityPolicy) Reset() {
	*x = SecurityPolicy{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityPolicy) ProtoMessage() {}

func (x *SecurityPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityPolicy.ProtoReflect.Descriptor instead.
func (*SecurityPolicy) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{7}
}

func (x *SecurityPolicy) GetBlockExec() bool {
	if x != nil {
		return x.BlockExec
	}
	return false
}

func (x *SecurityPolicy) GetAllowedImages() []string {
	if x != nil {
		return x.AllowedImages
	}
	return nil
}

type SetSecurityPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *SecurityPolicy        `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecurityPolicyRequest) Reset() {
	*x = SetSecurityPolicyRequest{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecurityPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecurityPolicyRequest) ProtoMessage() {}

func (x *SetSecurityPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecurityPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetSecurityPolicyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{8}
}

func (x *SetSecurityPolicyRequest) GetPolicy() *SecurityPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type SetSecurityPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecurityPolicyResponse) Reset() {
	*x = SetSecurityPolicyResponse{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecurityPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecurityPolicyResponse) ProtoMessage() {}

func (x *SetSecurityPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecurityPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetSecurityPolicyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{9}
}

type GetSecurityPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecurityPolicyRequest) Reset() {
	*x = GetSecurityPolicyRequest{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityPolicyRequest) ProtoMessage() {}

func (x *GetSecurityPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetSecurityPolicyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{10}
}

type GetSecurityPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *SecurityPolicy        `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecurityPolicyResponse) Reset() {
	*x = GetSecurityPolicyResponse{}
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityPolicyResponse) ProtoMessage() {}

func (x *GetSecurityPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_portals_proto_configurator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetSecurityPolicyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_portals_proto_configurator_proto_rawDescGZIP(), []int{11}
}

func (x *GetSecurityPolicyResponse) GetPolicy() *SecurityPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

var File_pkg_portals_proto_configurator_proto protoreflect.FileDescriptor

const file_pkg_portals_proto_configurator_proto_rawDesc = "" +
	"\n" +
	"$pkg/portals/proto/configurator.proto\x12\aportals\"\x9c\x01\n" +
	"\bRuleSpec\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1f\n" +
	"\vrewrite_url\x18\x02 \x01(\tR\n" +
	"rewriteUrl\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\x12\x1f\n" +
	"\vauth_header\x18\x04 \x01(\tR\n" +
	"authHeader\x12\x1b\n" +
	"\tcache_ttl\x18\x05 \x01(\tR\bcacheTtl\"\x1e\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"b\n" +
	"\n" +
	"PortalRule\x12-\n" +
	"\bmetadata\x18\x01 \x01(\v2\x11.portals.MetadataR\bmetadata\x12%\n" +
	"\x04spec\x18\x02 \x01(\v2\x11.portals.RuleSpecR\x04spec\"?\n" +
	"\x12UpdateRulesRequest\x12)\n" +
	"\x05rules\x18\x01 \x03(\v2\x13.portals.PortalRuleR\x05rules\"\x15\n" +
	"\x13UpdateRulesResponse\"\x12\n" +
	"\x10ListRulesRequest\">\n" +
	"\x11ListRulesResponse\x12)\n" +
	"\x05rules\x18\x01 \x03(\v2\x13.portals.PortalRuleR\x05rules\"V\n" +
	"\x0eSecurityPolicy\x12\x1d\n" +
	"\n" +
	"block_exec\x18\x01 \x01(\bR\tblockExec\x12%\n" +
	"\x0eallowed_images\x18\x02 \x03(\tR\rallowedImages\"K\n" +
	"\x18SetSecurityPolicyRequest\x12/\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.portals.SecurityPolicyR\x06policy\"\x1b\n" +
	"\x19SetSecurityPolicyResponse\"\x1a\n" +
	"\x18GetSecurityPolicyRequest\"L\n" +
	"\x19GetSecurityPolicyResponse\x12/\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.portals.SecurityPolicyR\x06policy2\xdd\x02\n" +
	"\x15SidecarReconfigurator\x12H\n" +
	"\vUpdateRules\x12\x1b.portals.UpdateRulesRequest\x1a\x1c.portals.UpdateRulesResponse\x12B\n" +
	"\tListRules\x12\x19.portals.ListRulesRequest\x1a\x1a.portals.ListRulesResponse\x12Z\n" +
	"\x11SetSecurityPolicy\x12!.portals.SetSecurityPolicyRequest\x1a\".portals.SetSecurityPolicyResponse\x12Z\n" +
	"\x11GetSecurityPolicy\x12!.portals.GetSecurityPolicyRequest\x1a\".portals.GetSecurityPolicyResponseB7Z5github.com/gke-labs/service-portals/pkg/portals/protob\x06proto3"

var (
	file_pkg_portals_proto_configurator_proto_rawDescOnce sync.Once
	file_pkg_portals_proto_configurator_proto_rawDescData []byte
)

func file_pkg_portals_proto_configurator_proto_rawDescGZIP() []byte {
	file_pkg_portals_proto_configurator_proto_rawDescOnce.Do(func() {
		file_pkg_portals_proto_configurator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_portals_proto_configurator_proto_rawDesc), len(file_pkg_portals_proto_configurator_proto_rawDesc)))
	})
	return file_pkg_portals_proto_configurator_proto_rawDescData
}

var file_pkg_portals_proto_configurator_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_portals_proto_configurator_proto_goTypes = []any{
	(*RuleSpec)(nil),                  // 0: portals.RuleSpec
	(*Metadata)(nil),                  // 1: portals.Metadata
	(*PortalRule)(nil),                // 2: portals.PortalRule
	(*UpdateRulesRequest)(nil),        // 3: portals.UpdateRulesRequest
	(*UpdateRulesResponse)(nil),       // 4: portals.UpdateRulesResponse
	(*ListRulesRequest)(nil),          // 5: portals.ListRulesRequest
	(*ListRulesResponse)(nil),         // 6: portals.ListRulesResponse
	(*SecurityPolicy)(nil),            // 7: portals.SecurityPolicy
	(*SetSecurityPolicyRequest)(nil),  // 8: portals.SetSecurityPolicyRequest
	(*SetSecurityPolicyResponse)(nil), // 9: portals.SetSecurityPolicyResponse
	(*GetSecurityPolicyRequest)(nil),  // 10: portals.GetSecurityPolicyRequest
	(*GetSecurityPolicyResponse)(nil), // 11: portals.GetSecurityPolicyResponse
}
var file_pkg_portals_proto_configurator_proto_depIdxs = []int32{
	1,  // 0: portals.PortalRule.metadata:type_name -> portals.Metadata
	0,  // 1: portals.PortalRule.spec:type_name -> portals.RuleSpec
	2,  // 2: portals.UpdateRulesRequest.rules:type_name -> portals.PortalRule
	2,  // 3: portals.ListRulesResponse.rules:type_name -> portals.PortalRule
	7,  // 4: portals.SetSecurityPolicyRequest.policy:type_name -> portals.SecurityPolicy
	7,  // 5: portals.GetSecurityPolicyResponse.policy:type_name -> portals.SecurityPolicy
	3,  // 6: portals.SidecarReconfigurator.UpdateRules:input_type -> portals.UpdateRulesRequest
	5,  // 7: portals.SidecarReconfigurator.ListRules:input_type -> portals.ListRulesRequest
	8,  // 8: portals.SidecarReconfigurator.SetSecurityPolicy:input_type -> portals.SetSecurityPolicyRequest
	10, // 9: portals.SidecarReconfigurator.GetSecurityPolicy:input_type -> portals.GetSecurityPolicyRequest
	4,  // 10: portals.SidecarReconfigurator.UpdateRules:output_type -> portals.UpdateRulesResponse
	6,  // 11: portals.SidecarReconfigurator.ListRules:output_type -> portals.ListRulesResponse
	9,  // 12: portals.SidecarReconfigurator.SetSecurityPolicy:output_type -> portals.SetSecurityPolicyResponse
	11, // 13: portals.SidecarReconfigurator.GetSecurityPolicy:output_type -> portals.GetSecurityPolicyResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_portals_proto_configurator_proto_init() }
func file_pkg_portals_proto_configurator_proto_init() {
	if File_pkg_portals_proto_configurator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_portals_proto_configurator_proto_rawDesc), len(file_pkg_portals_proto_configurator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_portals_proto_configurator_proto_goTypes,
		DependencyIndexes: file_pkg_portals_proto_configurator_proto_depIdxs,
		MessageInfos:      file_pkg_portals_proto_configurator_proto_msgTypes,
	}.Build()
	File_pkg_portals_proto_configurator_proto = out.File
	file_pkg_portals_proto_configurator_proto_goTypes = nil
	file_pkg_portals_proto_configurator_proto_depIdxs = nil
}
