// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/portals/proto/configurator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SidecarReconfigurator_UpdateRules_FullMethodName       = "/portals.SidecarReconfigurator/UpdateRules"
	SidecarReconfigurator_ListRules_FullMethodName         = "/portals.SidecarReconfigurator/ListRules"
	SidecarReconfigurator_SetSecurityPolicy_FullMethodName = "/portals.SidecarReconfigurator/SetSecurityPolicy"
	SidecarReconfigurator_GetSecurityPolicy_FullMethodName = "/portals.SidecarReconfigurator/GetSecurityPolicy"
)

// SidecarReconfiguratorClient is the client API for SidecarReconfigurator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SidecarReconfiguratorClient interface {
	UpdateRules(ctx context.Context, in *UpdateRulesRequest, opts ...grpc.CallOption) (*UpdateRulesResponse, error)
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	SetSecurityPolicy(ctx context.Context, in *SetSecurityPolicyRequest, opts ...grpc.CallOption) (*SetSecurityPolicyResponse, error)
	GetSecurityPolicy(ctx context.Context, in *GetSecurityPolicyRequest, opts ...grpc.CallOption) (*GetSecurityPolicyResponse, error)
}

type sidecarReconfiguratorClient struct {
	cc grpc.ClientConnInterface
}

func NewSidecarReconfiguratorClient(cc grpc.ClientConnInterface) SidecarReconfiguratorClient {
	return &sidecarReconfiguratorClient{cc}
}

func (c *sidecarReconfiguratorClient) UpdateRules(ctx context.Context, in *UpdateRulesRequest, opts ...grpc.CallOption) (*UpdateRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRulesResponse)
	err := c.cc.Invoke(ctx, SidecarReconfigurator_UpdateRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarReconfiguratorClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, SidecarReconfigurator_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarReconfiguratorClient) SetSecurityPolicy(ctx context.Context, in *SetSecurityPolicyRequest, opts ...grpc.CallOption) (*SetSecurityPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSecurityPolicyResponse)
	err := c.cc.Invoke(ctx, SidecarReconfigurator_SetSecurityPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarReconfiguratorClient) GetSecurityPolicy(ctx context.Context, in *GetSecurityPolicyRequest, opts ...grpc.CallOption) (*GetSecurityPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecurityPolicyResponse)
	err := c.cc.Invoke(ctx, SidecarReconfigurator_GetSecurityPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SidecarReconfiguratorServer is the server API for SidecarReconfigurator service.
// All implementations must embed UnimplementedSidecarReconfiguratorServer
// for forward compatibility.
type SidecarReconfiguratorServer interface {
	UpdateRules(context.Context, *UpdateRulesRequest) (*UpdateRulesResponse, error)
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	SetSecurityPolicy(context.Context, *SetSecurityPolicyRequest) (*SetSecurityPolicyResponse, error)
	GetSecurityPolicy(context.Context, *GetSecurityPolicyRequest) (*GetSecurityPolicyResponse, error)
	mustEmbedUnimplementedSidecarReconfiguratorServer()
}

// UnimplementedSidecarReconfiguratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSidecarReconfiguratorServer struct{}

func (UnimplementedSidecarReconfiguratorServer) UpdateRules(context.Context, *UpdateRulesRequest) (*UpdateRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRules not implemented")
}
func (UnimplementedSidecarReconfiguratorServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedSidecarReconfiguratorServer) SetSecurityPolicy(context.Context, *SetSecurityPolicyRequest) (*SetSecurityPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSecurityPolicy not implemented")
}
func (UnimplementedSidecarReconfiguratorServer) GetSecurityPolicy(context.Context, *GetSecurityPolicyRequest) (*GetSecurityPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecurityPolicy not implemented")
}
func (UnimplementedSidecarReconfiguratorServer) mustEmbedUnimplementedSidecarReconfiguratorServer() {}
func (UnimplementedSidecarReconfiguratorServer) testEmbeddedByValue()                               {}

// UnsafeSidecarReconfiguratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SidecarReconfiguratorServer will
// result in compilation errors.
type UnsafeSidecarReconfiguratorServer interface {
	mustEmbedUnimplementedSidecarReconfiguratorServer()
}

func RegisterSidecarReconfiguratorServer(s grpc.ServiceRegistrar, srv SidecarReconfiguratorServer) {
	// If the following call pancis, it indicates UnimplementedSidecarReconfiguratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SidecarReconfigurator_ServiceDesc, srv)
}

func _SidecarReconfigurator_UpdateRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarReconfiguratorServer).UpdateRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarReconfigurator_UpdateRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarReconfiguratorServer).UpdateRules(ctx, req.(*UpdateRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarReconfigurator_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarReconfiguratorServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarReconfigurator_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarReconfiguratorServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarReconfigurator_SetSecurityPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecurityPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarReconfiguratorServer).SetSecurityPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarReconfigurator_SetSecurityPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarReconfiguratorServer).SetSecurityPolicy(ctx, req.(*SetSecurityPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarReconfigurator_GetSecurityPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecurityPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarReconfiguratorServer).GetSecurityPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarReconfigurator_GetSecurityPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarReconfiguratorServer).GetSecurityPolicy(ctx, req.(*GetSecurityPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SidecarReconfigurator_ServiceDesc is the grpc.ServiceDesc for SidecarReconfigurator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SidecarReconfigurator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portals.SidecarReconfigurator",
	HandlerType: (*SidecarReconfiguratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateRules",
			Handler:    _SidecarReconfigurator_UpdateRules_Handler,
		},
		{
			MethodName: "ListRules",
			Handler:    _SidecarReconfigurator_ListRules_Handler,
		},
		{
			MethodName: "SetSecurityPolicy",
			Handler:    _SidecarReconfigurator_SetSecurityPolicy_Handler,
		},
		{
			MethodName: "GetSecurityPolicy",
			Handler:    _SidecarReconfigurator_GetSecurityPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/portals/proto/configurator.proto",
}
